settings:
  - name: layout
    description: 'setting.layout.description'
    type: choice
    type_options: { expanded: true, multiple: false }
    choices: ['setting.layout.boxed', 'setting.layout.wide']
    data: 'setting.layout.boxed'
  - name: footer_text
    description: 'setting.footer_text.description'
    type: string